version: '3'

services:
  mongodb:
    image: mongo:5
    env_file: ./.env
    logging:
      driver: none
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    ports:
      - $MONGODB_LOCAL_PORT:$MONGODB_DOCKER_PORT
    volumes:
      - db:/data/db
  go:
    depends_on:
      - mongodb
    build: .
    env_file: ./.env
    ports:
      - "$PORT:8080"

volumes:
  db:
